debug = false
checkNewVersion = true
logLevel = "WARN"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

# https://docs.traefik.io/configuration/commons/#retry-configuration
# Enable retry sending request if network error
[retry]

# https://docs.traefik.io/configuration/backends/docker/
[docker]
# Required for traefik to get services metadata from docker
# Can be mounted as readonly in docker-compose.yml
endpoint = "unix:///var/run/docker.sock"
# Watch for docker changes
watch = true

# (Optional) Expose containers by default in Traefik.
# If set to false, containers that don't have `traefik.enable=true` will be ignored.
# Default: true
exposedbydefault = false

# Use Swarm Mode services as data provider.
# true when using swarm (docker stack deploy)
# false when using docker-compose (docker-compose up)
# NOTE:
#   labels on swarm mode are under service.deploy.labels
#   labels on docker-compose mode are under service.labels (no deploy section)
swarmmode = true
