sudo: required

env:
    global:
        - DOCKER_PASSWORD: ''
        - DOCKER_USERNAME: ''

services:
    - docker

before_install:
    - docker build -t basmalltalk/pharo:6.1

deploy:
    provider: script
    script: bash docker_push
    on:
        branch: master

