sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=basmalltalk/pharo:6.1
  - secure: cKTGc6ti6SuWqO8WV9ZJpFRyyaE/Wj3RcdbzQhSkFxSuMd08fyfhUS1QrICIaByCaE17YeMJGFHwqacR3Q264JnUKDS0Rs7ZHCbT24tGCdA4i0AeKXeGQXx1p/+tY26J3udQiQWMAhsjGJfxkqhIMW+OGYI2EQHrHs3sZf0mzTgIuLMnSLmOXcYEgYfBSRnn70hc/OK7A27reCdd9ZAFmChxKhq2FDYmW3JjleiXT+YH+SXmDVM+D+yJGuUwYCk80PnXLKTOdyR1SoghWVV3nqSl6/I9rCpQskGTliRxvROYIgYQZobpTORWMpWlizbTtR6JUCmXr0OffS3nyUF11++7S9QbFKiuYRQQZMnMZuDlKKSj9f14mpk6T0yLKhmEeGNXt5HNTD6hTIVo7GMyAVDc0V9eko3+6KANvb79lodn+Eo0OyEwo2tU6Ylrqj4seBIyDE5IFap3tJ3vU4f+v2rWLEviO/z8f+KdZvAMV42OQt+YUj3iVphI7uCp1GQeo0Kue9SwdEvgRBYnwxwF6tyRSGvIgryR6zdG02jnF0yadsNK0Fg9xpN7KrUnmbefNRnI3ECqs3OiuwY1uYVABHu/3CrU66CfAvJMPYcjZoYG+DscNGZ/xKJFoXnbbAGUNcfMPhNDerizesw7eGOtg6+d+zM1ThIpgRRe5MBv5fc=
  - secure: X9zIhFk0QzP8Ej4NSGABtugwbtHRs/xu7t249KNMmWCKUF+HFxjXCBwu/p9MzFOsZbdyVi7p+jrujZvt0s39DWPzGxI0DaPbPhba02MQ1G8u8cNUKCrBeVnzT+H4WRLaNqpxleg+IhHhK9iy+Q5IeCVXT3TC87EztaaCg3kVCy7qh7RnH66jFAJB8aNqI70wGbyVnF/h6xiVUMALR/5GW/qAI3n1eHR66iuOL1tgNxL7AcSISHYpf1nT4L0Q14NLQ2qBKMMy83maqm8PxiseT462pfkmclOuwP6QnfL29ggQGSsvvEnABv2gZZoxq/LGd5l9BcTeAB+GkiswIX3h8sVHLy5DtRTCl4z/UTjrmlBJo+rZAkW6gVhL0vh6p5Z3QUhrA9GVa4FP3yhCmwRmM80nJEOo4s7Z9IwFwZuhdQXb3J3lk3WA7vimqjhboVWI5JOqLqe7W6NwFLnUN13x9fzwxQaJ+EXOnoWRUSkzJXrBqCWTSI8GuYlkAcYxqIUX+LCC2JY+Kv27ZA5FOamj6jFQkw3mumYjhQbMK2G9kjzdGJrSPz1Ow/URN2l1ZcyqSdTVMm9uN5gffjmMzOW0KQ9DfdpCBpVTmzqxsO0Agh5oi24qrB5mfMqDRJI6t1EQAKQCEmigpgEMfGUrmiTejUne+9cSA8sZ8tQQGlJmAW8=
before_script:
- docker pull "$IMAGE_NAME" || true
script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}"
  on:
    branch: master
