language: minimal

services:
  - docker

script:
  - docker build 6.1 --target vm --tag basmalltalk/pharo:6.1
  - docker build 6.1 --target image --tag basmalltalk/pharo:6.1-image
  - docker-compose --file 6.1/docker-compose.test.yml up --exit-code-from sut
  - docker build 7.0 --target vm --tag basmalltalk/pharo:7.0
  - docker build 7.0 --target image --tag basmalltalk/pharo:7.0-image
  - docker-compose --file 7.0/docker-compose.test.yml up --exit-code-from sut
  - docker build docs/examples/pharo-date
  - docker build docs/examples/pharo-date-multistage