#!/bin/bash
set -eu

VERSION=$DOCKER_TAG
# shellcheck disable=SC2072
if [[ $VERSION < '7.0' ]]
then BASE_TAG=base-32
else BASE_TAG=base-64
fi

docker build \
  --cache-from "$DOCKER_REPO:$BASE_TAG" \
  --file "$DOCKERFILE_PATH" \
  --tag "$DOCKER_REPO:$BASE_TAG" \
  --target base \
  .
docker build \
  --cache-from "$DOCKER_REPO:$BASE_TAG" \
  --cache-from "$IMAGE_NAME" \
  --file "$DOCKERFILE_PATH" \
  --tag "$IMAGE_NAME" \
  --target vm \
  .
docker build \
  --cache-from "$IMAGE_NAME" \
  --cache-from "$IMAGE_NAME" \
  --file "$DOCKERFILE_PATH" \
  --tag "$IMAGE_NAME-image" \
  --target image \
  .
